CREATE DATABASE SaleDB

GO

USE SaleDB

GO
CREATE TABLE ACCOUNTANT_ACCOUNT(
	AC_ID VARCHAR(10) NOT NULL UNIQUE,
	AC_NAME VARCHAR(50) NOT NULL,
	AC_GENDER VARCHAR(6) NOT NULL,
	AC_EMAIL VARCHAR(50) NOT NULL,
	AC_PHONENUM VARCHAR(10) NOT NULL,
	AC_ADDRESS VARCHAR(65) NOT NULL,
	PRIMARY KEY(AC_ID)
)
GO
CREATE TABLE ITEM(
	ITEM_ID VARCHAR(10) NOT NULL UNIQUE,
	ITEM_NAME VARCHAR(45) NOT NULL,
	ITEM_CATEGORY VARCHAR(20),
	ITEM_FUNCTION VARCHAR(25),
	ITEM_BRAND VARCHAR(30),
	ITEM_PRICE MONEY,
	ITEM_DESCRIPTION VARCHAR(170),
	ISPRESCRIPTION BIT,
	CONSTRAINT CK_BOOL_ISPRE CHECK (ISPRESCRIPTION IN (1,0)),
	PRIMARY KEY (ITEM_ID)
)
GO
CREATE TABLE COMPANY(
	COMPANY_NAME VARCHAR(90) NOT NULL UNIQUE,
	COMPANY_EMAIL VARCHAR(50) NOT NULL,
	COMPANY_PHONE VARCHAR(10) ,
	COMPANY_ADDRESS VARCHAR(55) NOT NULL,
	PRIMARY KEY(COMPANY_NAME)
)
GO
CREATE TABLE AGENCY_ACCOUNT(
	AGENCY_ID VARCHAR(10) NOT NULL UNIQUE,
	AGENCY_NAME VARCHAR(90),
	AGENCY_ADDRESS VARCHAR(55),
	AGENCY_EMAIL VARCHAR(50),
	AGENCY_PHONE VARCHAR(10),
	PRIMARY KEY (AGENCY_ID)
)


CREATE TABLE WAREHOUSE (
	WAREHOUSE_ID VARCHAR(10) NOT NULL UNIQUE,
	WAREHOUSE_NAME VARCHAR(45),
	WAREHOUSE_ADDRESS VARCHAR(55),
	WAREHOUSE_PHONE VARCHAR(10),
	WAREHOUSE_MANAGERNAME VARCHAR (50),
	WAREHOUSE_SIZE INT,
	WAREHOUSE_CAPACITY INT
	PRIMARY KEY (WAREHOUSE_ID)
)
GO
CREATE TABLE IMPORTRECEIPT(
	RECEIPT_ID VARCHAR(10) NOT NULL UNIQUE,
	ITEM_ID VARCHAR(10) NOT NULL,
	AC_ID VARCHAR(10) NOT NULL,
	WAREHOUSE_ID VARCHAR(10) NOT NULL,
	ITEM_QUANTITY INT,
	IMPORT_DATE DATE,
	TOTAL_MONEY MONEY,
	PRIMARY KEY (RECEIPT_ID) ,
	FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID),
	FOREIGN KEY (AC_ID) REFERENCES ACCOUNTANT_ACCOUNT(AC_ID),
	FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID)
)
GO
CREATE TABLE EXPORTRECEIPT(
	ORDER_NUM VARCHAR(10) NOT NULL UNIQUE,
	AGENCY_ID VARCHAR(10) NOT NULL,
	WAREHOUSE_ID VARCHAR(10) NOT NULL,
	ITEM_ID VARCHAR(10) NOT NULL,
	ITEM_QUANTITY INT,
	TOTAL_MONEY MONEY,
	DATE_DISPATCHED DATE,
	EXPECTED_DELIVERY_DATE DATE,
	PRIMARY KEY (ORDER_NUM),
	FOREIGN KEY (AGENCY_ID) REFERENCES AGENCY_ACCOUNT(AGENCY_ID),
	FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID),
	FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID)
)
